### ISSUE TITLE
Not Compatible with EPiServer.CMS.Core.10.8.0!

### ISSUE THREAD

**Issue by ajainabhi** [casper-rasmussen/Fellow.Epi.JobNotifier#1]
I am using Episerver version (EPiServer.CMS.Core.10.8.0), in this version it is not compatible, So could you 
please look at it and update this?

Regards

**Comment by casper-rasmussen** [comment]
Fixed. Sorry for the late attention on this - better late than never. Hope the new compatibility helps others besides yourself.
